apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spell-check-api
  name: spell-check-api
  selfLink: /api/v1/namespaces/default/services/spell-check-api
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spell-check-api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
